---
apiVersion: v1
kind: Namespace
metadata:
  name: simple-web
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-web
  namespace: simple-web
spec:
  replicas: 3
  selector:
    matchLabels:
      app: simple-web
  template:
    metadata:
      labels:
        app: simple-web
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - simple-web
              topologyKey: "kubernetes.io/hostname"
      containers:
      - name: web
        image: yeasy/simple-web:latest
        ports:
        - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: simple-web-service
  namespace: simple-web
spec:
  selector:
    app: simple-web
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: NodePort 

---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: simple-web-pdb
  namespace: simple-web
spec:
  selector:
    matchLabels:
      app: simple-web
  minAvailable: 2
